load(":textproto_indexer_test.bzl", "textproto_indexer_test")

textproto_indexer_test(
    name = "test_example_bz",
    message_name = "example.MyMessage",
    protos = ["example.proto"],
    textproto = "example.pbtxt",
)
